// Auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGINS_FAILED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAILED = "LOAD_USER_FAILED";
export const LOG_OUT = "LOG_OUT";

// Question Bank
export const GET_QUESTION_BANK_SUCCESS = "GET_QUESTION_BANK_SUCCESS";
export const GET_QUESTION_BANK_FAILED = "GET_QUESTION_BANK_FAILED";
export const GET_CHAPTER_SUCCESS = "GET_CHAPTER_SUCCESS";
export const GET_CHAPTER_FAILED = "GET_CHAPTER_FAILED";
export const GENERATE_QUIZ_SUCCESS = "GENERATE_QUIZ_SUCCESS";
export const GENERATE_QUIZ_FAILED = "GENERATE_QUIZ_FAILED";
export const CLEAR_QUIZ = "CLEAR_QUIZ";
export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";
export const GET_QUESTIONS_FAILED = "GET_QUESTIONS_FAILED";
export const GET_QUESTION_FAILED = "GET_QUESTION_FAILED";
export const GET_QUESTION_SUCCESS = "GET_QUESTION_FAILED";
// User
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPLOAD_AVATAR_SUCCESS = "UPLOAD_AVATAR_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";
export const UPLOAD_AVATAR_FAILED = "UPLOAD_AVATAR_FAILED";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
export const ADD_COURSE_FAILED = "ADD_COURSE_FAILED";
export const REMOVE_COURSE_SUCCESS = "REMOVE_COURSE_SUCCESS";
export const REMOVE_COURSE_FAILED = "REMOVE_COURSE_FAILED";
export const GET_USER_CHAPTER_SUCCESS = "GET_USER_CHAPTER_SUCCESS";
export const GET_USER_CHAPTER_FAILED = "GET_USER_CHAPTER_FAILED";
// Note
export const ADD_NOTE_SUCCESS = "ADD_NOTE_SUCCESS";
export const ADD_NOTE_FAILED = "ADD_NOTE_FAILED";
export const GET_NOTE_SUCCESS = "GET_NOTE_SUCCESS";
export const GET_NOTE_FAILED = "GET_NOTE_FAILED";
export const GET_USER_NOTE_SUCCESS = "GET_USER_NOTE_SUCCESS";
export const GET_USER_NOTE_FAILED = "GET_USER_NOTE_FAILED";
export const UPDATE_USER_NOTE_SUCCESS = "UPDATE_USER_NOTE_SUCCESS";
export const UPDATE_USER_NOTE_FAILED = "UPDATE_USER_NOTE_FAILED";
export const CLEAR_NOTE = "CLEAR_NOTE";
// Vote
export const VOTE_SUCCESS = "VOTE_SUCCESS";
export const VOTE_FAILED = "VOTE_FAILED";

// Comment
export const GET_QUESTION_COMMENT_SUCCESS = "GET_QUESTION_COMMENT_SUCCESS";
export const GET_QUESTION_COMMENT_FAILED = "GET_QUESTION_COMMENT_FAILED";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILED = "CREATE_COMMENT_FAILED";
